### ISSUE TITLE
Crash after double click on person

### ISSUE THREAD

**Issue by Marmo** [Marmo/debitum#58]
App crashes when double-clicking on a person in the People list
```
Process: org.ebur.debitum.debug, PID: 23709
    java.lang.IllegalArgumentException: Navigation action/destination org.ebur.debitum.debug:id/action_personSumList_to_transactionList_on_filter cannot be found from the current destination Destination(org.ebur.debitum.debug:id/money_dest) label=Geld class=org.ebur.debitum.ui.TransactionListFragment
        at androidx.navigation.NavController.navigate(NavController.java:940)
        at org.ebur.debitum.ui.PersonSumListViewHolder.onClick(PersonSumListViewHolder.java:99)
```

**Comment by Bufkin** [comment]
I can't reproduce this issue on the latest version on Android 11.

**Comment by Marmo** [comment]
can't reproduce anymore - closing
